#ifndef PL_H
#define PL_H

#define PL_COMMAND_SIZE 2
#define PL_COMMAND_PARAM_SIZE 1
#define PL_QUERY_SIZE PL_COMMAND_SIZE
#define PL_QUERY_PARAM_SIZE PL_COMMAND_PARAM_SIZE

#define PL_START_BYTE 0x4A
#define PL_START_BYTE_SIZE 1
#define PL_QUERY_LENGTH_SIZE 1
#define PL_QUERY_MAX_LENGTH 0xff
#define PL_INTERRUPT_BYTE 0xA4

typedef enum
{
    PL_COMMAND_IGNORE,
    PL_COMMAND_STOP,
    PL_COMMAND_POWER_OFF,
    PL_COMMAND_POWER_ON,
    PL_COMMAND_SWEEP,
    PL_COMMAND_DEPLOY,
    PL_COMMAND_DEPLOY_SP,
    PL_COMMAND_DEPLOY_FP,
    PL_COMMAND_CLEAR_ERRORS,
    PL_COMMAND_ENUM_COUNT,
    PL_COMMAND_INVALID = 0xFF
} PL_Command_t;

typedef enum
{
    PL_QUERY_EVENT = PL_COMMAND_ENUM_COUNT,
    PL_QUERY_ERROR_STATUS,
    PL_QUERY_DEPLOYMENT_STATE,
    PL_QUERY_PROBE_POWER,
    PL_QUERY_PROBE_TEMPERATURE,
    PL_QUERY_PROBE_DIGIPOT,
    PL_QUERY_PROBE_FP,
    PL_QUERY_DAC,
    PL_QUERY_16V_POWER_CUR,
    PL_QUERY_CONTACT_SWITCH,
    PL_QUERY_SAMPLING_DATA,
    PL_QUERY_INVALID = 0xFF
} PL_Query_t;

typedef enum
{
    PL_EVENT_TASK_INTERRUPTED,
    PL_EVENT_TASK_BUSY,
    PL_EVENT_ERROR,
    PL_EVENT_PROBE_UNPOWERED,
    PL_EVENT_PROBE_POWERED,
    PL_EVENT_SWEEP_STARTED,
    PL_EVENT_SWEEP_COMPLETE,
    PL_EVENT_DEPLOY_STARTED,
    PL_EVENT_DEPLOY_COMPLETE,
    PL_EVENT_DEPLOY_FP_STARTED,
    PL_EVENT_DEPLOY_FP_COMPLETE,
    PL_EVENT_DEPLOY_SP_STARTED,
    PL_EVENT_DEPLOY_SP_COMPLETE,
    PL_EVENT_INVALID = 0xFF
} PL_Event_t;

#endif /* PL_H */
